name: Deploy Stack to AWS 🟢

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password for deployment'
        required: true
        type: string

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    env:
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}

    outputs:
      LoadBalancerUrl: ${{ steps.get-outputs.outputs.LoadBalancerUrl }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate Password
        id: password-check
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.DEPLOY_PASSWORD }}" ]; then
            echo "Invalid password"
            exit 1
          fi
          echo "Password validated successfully"

      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build Auth Service
        run: pnpm run build:auth

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_AWS_ROLE }}
          aws-region: ap-south-1

      - name: Build CDK
        run: pnpm run cdk:build

      - name: Run Synth CDK
        run: pnpm run cdk:synth

      - name: Deploy Stack
        run: pnpm run cdk:deploy
