name: Deploy Stack to AWS 🟢

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password for deployment'
        required: true
        type: string

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}

    outputs:
      LoadBalancerUrl: ${{ steps.get-outputs.outputs.LoadBalancerUrl }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate Password
        id: password-check
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.DEPLOY_PASSWORD }}" ]; then
            echo "Invalid password"
            exit 1
          fi
          echo "Password validated successfully"

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install project dependencies
        run: pnpm --prefer-offline

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Build
        run: pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_AWS_ROLE }}
          aws-region: ap-south-1
        
      - name: Build CDK
        run: pnpm run cdk:build

      - name: Run Synth CDK
        run: pnpm run cdk:synth

      - name: Deploy Stack
        run: pnpm run cdk:deploy